"""Initial schema

Revision ID: b1ec31c11489
Revises: 
Create Date: 2025-10-15 12:56:20.929250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ec31c11489'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('natural_key', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('area', sa.String(length=500), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_effective_at', 'alerts', ['effective_at'], unique=False)
    op.create_index('idx_alerts_source_provider', 'alerts', ['source', 'provider_id'], unique=False)
    op.create_index(op.f('ix_alerts_effective_at'), 'alerts', ['effective_at'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_natural_key'), 'alerts', ['natural_key'], unique=True)
    op.create_index(op.f('ix_alerts_source'), 'alerts', ['source'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_alert_id'), 'classifications', ['alert_id'], unique=False)
    op.create_index(op.f('ix_classifications_criticality'), 'classifications', ['criticality'], unique=False)
    op.create_index(op.f('ix_classifications_id'), 'classifications', ['id'], unique=False)
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_actions_alert_action', 'user_actions', ['alert_id', 'action'], unique=False)
    op.create_index(op.f('ix_user_actions_alert_id'), 'user_actions', ['alert_id'], unique=False)
    op.create_index(op.f('ix_user_actions_id'), 'user_actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_actions_id'), table_name='user_actions')
    op.drop_index(op.f('ix_user_actions_alert_id'), table_name='user_actions')
    op.drop_index('idx_user_actions_alert_action', table_name='user_actions')
    op.drop_table('user_actions')
    op.drop_index(op.f('ix_classifications_id'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_criticality'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_alert_id'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_alerts_source'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_natural_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_effective_at'), table_name='alerts')
    op.drop_index('idx_alerts_source_provider', table_name='alerts')
    op.drop_index('idx_alerts_effective_at', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###

