"""Add latitude and longitude fields to alerts

Revision ID: f67b3df96b59
Revises: b1ec31c11489
Create Date: 2025-10-29 19:21:42.557792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67b3df96b59'
down_revision = 'b1ec31c11489'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_index('idx_alerts_location', 'alerts', ['latitude', 'longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alerts_location', table_name='alerts')
    op.drop_column('alerts', 'longitude')
    op.drop_column('alerts', 'latitude')
    # ### end Alembic commands ###

